stages:
  - build
  - test
  - test_js

build:
  stage: build
  script:
    - docker build  . --file=./docker/reports/Dockerfile --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  only:
    - branches
  tags:
    - shell
  except:
    - schedules
  variables:
    GIT_STRATEGY: fetch

variables:
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: admin

Python tests:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  tags:
    - kube
  only:
    - branches
  services:
    - couchdb:1.6
  script:
    - pip install mock nose coverage
    - nosetests --with-coverage  --cover-package=reports
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

Js tests:
  stage: test_js
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  tags:
    - kube
  only:
    - branches
  allow_failure: true
  cache:
    paths:
      - node_modules/
  script:
    - apt-get update
    - apt-get -y install curl gnupg
    - curl -sL https://deb.nodesource.com/setup_11.x  | bash -
    - apt-get -y --force-yes install nodejs
    - npm install
    - npm run test
