language:
  - python
python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
  - eggs
before_install:
  - sh bootstrap.sh
install:
  - bin/buildout -N
  - npm install
before_script:
  - curl -s -X PUT http://127.0.0.1:5984/_config/admins/admin -d '"admin"'
script:
  - npm run test
  - bin/nosetests -v
