language:
  - python
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
install:
  - pip install -r tests_requirements.txt
  - npm install
script:
  - npm run test
  - python -m nose
